
// for  adding post
export const POST_DATA_LOADING = "POST_DATA_LOADING";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_ERROR = "POST_DATA_ERROR";

// for update post
export const POST_DATA_UPDATE_LOADING = "POST_DATA_UPDATE_LOADING";
export const POST_DATA_UPDATE_SUCCESS = "POST_DATA_UPDATE_SUCCESS";
export const POST_DATA_UPDATE_ERROR = "POST_DATA_UPDATE_ERROR";

// for removing the post status
export const REMOVE_UPDATE_STATUS = "REMOVE_UPDATE_STATUS";
export const REMOVE_ADD_STATUS = "REMOVE_ADD_STATUS";
export const REMOVE_DELETE_STATUS = "REMOVE_DELETE_STATUS";

// for deleting post 
export const POST_DATA_DELETE_LOADING = "POST_DATA_DELETE_LOADING";
export const POST_DATA_DELETE_SUCCESS = "POST_DATA_DELETE_SUCCESS";
export const POST_DATA_DELETE_ERROR = "POST_DATA_DELETE_ERROR";
