export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_ERROR = "POST_DATA_ERROR";

export const POST_DATA_UPDATE_SUCCESS = "POST_DATA_UPDATE_SUCCESS";
export const POST_DATA_UPDATE_ERROR = "POST_DATA_UPDATE_ERROR";

export const REMOVE_STATUS = "REMOVE_UPDATE_STATUS";

export const POST_DATA_DELETE_SUCCESS = "POST_DATA_DELETE_SUCCESS";
export const POST_DATA_DELETE_ERROR = "POST_DATA_DELETE_ERROR";